function graphPotenciaIrrigacion(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  stairs x
%  Y1:  stairs y
N = 720;
X1 = (linspace(0, 43200, N))/60/60 + 6;

Y1_Temp = zeros(1, 720);
Y1_Temp(1:10:720) = Y1;
Y1 = Y1_Temp;
%  Auto-generated by MATLAB on 28-May-2020 00:10:06

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create stairs
stairs(X1,Y1,'Color',[0 0 0]);

% Create ylabel
ylabel('Potencia irrigación SBR [W]');

% Create xlabel
xlabel('Tiempo [horas]');

% Create title
title('Potencia de irrigación - SBR');

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Humanst521 BT','GridColor',[0 0 0],'GridLineStyle',...
    '--','XMinorGrid','on','YMinorGrid','on');

%% Guardar figura

numeroDia = i;

% ruta = '/MATLAB Drive/tangente-penitente/graficas/';
ruta = 'C:\Users\james\Documents\GitHub\tangente-penitente\graficas\SBR\';

nombreArchivo = [ruta, 'graphPotenciaIrrigacionSBR_Dia', num2str(i)];

%saveas(figure1, nombreArchivo, 'fig');
%saveas(figure1, nombreArchivo, 'png');
%close;

