function graphPotenciaIrrigacion(X1, Y1, i)
%CREATEFIGURE(X1, Y1)
%  X1:  stairs x
%  Y1:  stairs y

%  Auto-generated by MATLAB on 30-Oct-2019 19:26:26

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create stairs
stairs(X1,Y1,'Color',[0 0 0]);

% Create ylabel
ylabel('Potencia irrigación [W]');

% Create xlabel
xlabel('Tiempo [horas]');

% Create title
title('Potencia de irrigación');

box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Cambria Math','GridColor',[0 0 0],'GridLineStyle',...
    '--','XMinorGrid','on','YMinorGrid','on');

%% Guardar figura

numeroDia = i;

% ruta = '/MATLAB Drive/tangente-penitente/graficas/';
ruta = 'C:\Users\james\Documents\GitHub\tangente-penitente\graficas\Irrigacion\';

nombreArchivo = [ruta, 'graphPotenciaIrrigacion_Dia', num2str(i)];

saveas(figure1, nombreArchivo, 'fig');
saveas(figure1, nombreArchivo, 'png');
close;
