function graphVariablesBasicas(t, temperaturaAmbiente, irradiancia, velocidadViento)

%  Auto-generated by MATLAB on 13-Jun-2020 17:39:50

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(3,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(t,temperaturaAmbiente,'Parent',subplot1,'LineWidth',0.7,...
    'Color',[0.149019607843137 0.149019607843137 0.149019607843137]);

% Create ylabel
ylabel('T. ambiente [ºC]','FontName','Humanst521 BT');

% Create xlabel
xlabel('Hora','FontName','Humanist');

box(subplot1,'on');
hold(subplot1,'off');
% Set the remaining axes properties
set(subplot1,'FontName','Humanst521 BT','XGrid','on','YGrid','on');
% Create subplot
subplot2 = subplot(3,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(t,irradiancia,'Parent',subplot2,'LineWidth',0.7,'Color',[0 0 0]);

% Create ylabel
ylabel('Irradiancia [W/m^2]');

% Create xlabel
xlabel('Hora');

box(subplot2,'on');
hold(subplot2,'off');
% Set the remaining axes properties
set(subplot2,'FontName','Humanst521 BT','XGrid','on','YGrid','on');
% Create subplot
subplot3 = subplot(3,1,3,'Parent',figure1);
hold(subplot3,'on');

% Create plot
plot(t,velocidadViento,'Parent',subplot3,'Color',[0 0 0]);

% Create ylabel
ylabel('V. viento [m/s]');

% Create xlabel
xlabel('Hora');

box(subplot3,'on');
hold(subplot3,'off');
% Set the remaining axes properties
set(subplot3,'FontName','Humanst521 BT','XGrid','on','YGrid','on');
